USE STGANAC;

DELETE FROM TB_STG_AERODROMOS_PRIVADOS
DELETE FROM TB_STG_AERODROMOS_PUBLICOS
DELETE FROM TB_STG_AERODROMOS_INTERNACIONAIS
DELETE FROM TB_STG_AERONAVES
DELETE FROM TB_STG_CIDADE
DELETE FROM TB_STG_CIDADE_INTERNACIONAL
DELETE FROM TB_STG_DADOS_ESTATISTICOS_TRANSPORTE_AEREO
DELETE FROM TB_STG_EMPRESAS_AREAS_ESTRANGEIRAS
DELETE FROM TB_STG_EMPRESAS_AREAS_NACIONAIS
DELETE FROM TB_STG_ESTADO
DELETE FROM TB_STG_PAIS
DELETE FROM TB_STG_PAIS_COMPLEMENTO
DELETE FROM TB_STG_TARIFAS_DOMESTICAS
DELETE FROM TB_STG_TARIFAS_INTERNACIONAL
DELETE FROM TB_STG_VRA