USE STGANAC;

DROP TABLE TB_STG_AERODROMOS_PRIVADOS
DROP TABLE TB_STG_AERODROMOS_PUBLICOS
DROP TABLE TB_STG_AERODROMOS_INTERNACIONAIS
DROP TABLE TB_STG_AERONAVES
DROP TABLE TB_STG_CIDADE
DROP TABLE TB_STG_CIDADE_INTERNACIONAL
DROP TABLE TB_STG_DADOS_ESTATISTICOS_TRANSPORTE_AEREO
DROP TABLE TB_STG_EMPRESAS_AREAS_ESTRANGEIRAS
DROP TABLE TB_STG_EMPRESAS_AREAS_NACIONAIS
DROP TABLE TB_STG_ESTADO
DROP TABLE TB_STG_PAIS
DROP TABLE TB_STG_PAIS_COMPLEMENTO
DROP TABLE TB_STG_TARIFAS_DOMESTICAS
DROP TABLE TB_STG_TARIFAS_INTERNACIONAL
DROP TABLE TB_STG_VRA